name: anitune
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
dependencies:
  # General
  - python=3.10
  - pip>=24.0

  # Required dependencies for ani:
  - numpy>=1.24
  - pytorch::pytorch=2.3
  - pytorch::pytorch-cuda=11.8
  - typing_extensions>=4.0.0
  - h5py  # HDF5 backend for datasets
  - tqdm  # progress bar util

  # Compiled extensions (cuAEV and MNP):
  - setuptools>=64
  - setuptools-scm>=8
  - gxx_linux-64=11.4
  - gcc_linux-64=11.4
  - nvidia::cuda-libraries-dev=11.8
  - nvidia::cuda-cccl=11.8
  - nvidia::cuda-nvcc=11.8

  # Automatic linters / checkers / tests / CI
  - pre-commit  # Runs pre commit/push hooks
  - black  # Code formatter
  - flake8  # PEP8 linter
  - mypy  # Type checker

  # Non automatic
  - coverage  # Code coverage
  - pytest  # Python testing framework
  - cruft # Keep up with cookiecutter updates

  # CLI
  - typer  # Handy cli library with support for type checking
  - rich  # Colorful styles and terminal outputs

  # Training:
  - lightning=2.2.1
  - torchmetrics=1.3.2
  - tensorboard

  # Docs:
  - sphinx  # documentation framework, uses restructured text (.rst)
  - sphinx_rtd_theme
  - sphinx-gallery

  # Utils:
  - psutil
