name: ani-ftune
channels:
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
dependencies:
  # general
  - python >=3.8
  - pip  # python packaging tool

  # automatic linters / checkers / tests / CI
  - pre-commit  # runs pre commit/push hooks
  - black  # code formatter
  - flake8  # pep8 linter
  - autoflake  # remove unused imports / variables
  #- isort  # imports sorter and grouper
  #- bandit  # find security issues

  # non automatic
  - mypy  # type checker
  - pylint  # heavyweight linter
  - coverage  # code coverage
  - pytest  # python testing framework
  - cruft # keep up with cookiecutter updates

  # cli
  - typer  # handy cli library with support for type checking
  - rich  # colorful styles and terminal outputs
  #- click  # more involved cli library, backend for typer
  #- shellingham  # autodetect shell for auto completion

  # docs
  - sphinx  # documentation framework, uses restructured text (.rst)
  #- sphinx_rtd_theme  # nice theme for sphinx
  #- sphinx-gallery  # sphinx plugin

  # # numerical
  # - numpy  # multidimensional array support
  # - pandas  # csv support

  # # data
  # - pyarrow  # Parquet backend
  # - h5py  # HDF5 backend
  # - zarr  # Zarr backend

  # # scientific / math
  # - plotly  # interactive plotting
  # - matplotlib  # plotting
  # - pint  # units
  # - scipy  # general scientific utils
  # - sympy  # symbolic mathematical manipulation

  # # DL
  # - pytorch  # deep learning and cuda accelerated matrix computation
  # - pytorch_lightning  # pytorch wrapper framework
  # - wandb  # logging DL runs to cloud

  # # utils
  # - psutil  # process management
  # - pydantic  # data validation for BaseModels
  # - pyyaml  # yaml parser
  # - tqdm  # progress bars
  # - lark-parser

  # # web
  # - requests  # for https requests
  # - bs4  # beautiful soup 4, web scraping
