name: anitune
channels:
  - nodefaults
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
dependencies:
  ## Required dependencies to run TorchANI ##
  - python=3.11
  - pip>=24.0
  - numpy
  - typing_extensions>=4.0.0
  - h5py  # HDF5 backend for datasets
  - tqdm  # progress bar util
  - typer  # CLI support
  - rich  # CLI support
  - huggingface_hub

  # Optional dependencies follow:

  ## ASE interface ##
  # Used for molecular dynamics and for tests/tools/docs
  - ase

  ## cuAEV and MNP ##
  # For more details consult the "developer notes" section in README.md
  # If installing on macOS, or if CUDA GPU support is **disabled**, comment all lines on this block
  - setuptools>=64
  - setuptools-scm>=8
  - gxx_linux-64=12.2
  - gcc_linux-64=12.2
  # (comment the cuda-toolkit line for macOS)
  # CUDA Toolkit must be present in host, for instance, by installing:
  - nvidia::cuda-toolkit=12.9

  ## Running torchani/tests ##
  - coverage  # code coverage
  - black  # formatter
  - flake8  # linter
  - mypy  # type checking
  - pytest  # tests runner
  - pre_commit  # run pre commit hooks
  - parameterized  # parametrize test classes
  - expecttest  # indirect dependency of torch.testing
  # Extra data backends for tests:
  - pandas  # Parquet backend
  - pyarrow  # Parquet backend
  - zarr  # Zarr backend

  - matplotlib
  - jinja2  # Templating engine to build generated code and docs

  ## Building torchani/docs ##

  # Utils:
  - psutil
  - matplotlib
  - pandas

  - pip:
    - --index-url https://download.pytorch.org/whl/cu129
    - --extra-index-url https://pypi.python.org/simple
    - torch==2.8.*
    - torchani>=2.7
    - lightning
    - torchmetrics
    - tensorboard
