name: anitune
channels:
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
dependencies:
  # general
  - python=3.9
  - pip  # python packaging tool

  # automatic linters / checkers / tests / CI
  - pre-commit  # runs pre commit/push hooks
  - black  # code formatter
  - flake8  # pep8 linter
  - autoflake  # remove unused imports / variables

  # non automatic
  - mypy  # type checker
  - pylint  # heavyweight linter
  - coverage  # code coverage
  - pytest  # python testing framework
  - cruft # keep up with cookiecutter updates
  - h5py  # HDF5 backend

  # cli
  - typer  # handy cli library with support for type checking
  - rich  # colorful styles and terminal outputs

  # Core
  - numpy=1.20
  - mkl=2024.0.0
  - pytorch=1.13.1
  - cudatoolkit=11.6

  # Data
  - h5py  # HDF5 backend
  - pyyaml  # builtin datasets specification

  # Utils
  - tqdm  # progress bar

  # Ase interface (optional)
  - ase

  # Neurochem files (legacy)
  - lark-parser
  - requests

  # Training
  - lightning=2.2.1
  - torchmetrics=1.3.2
  - tensorboard

  # docs
  - sphinx  # documentation framework, uses restructured text (.rst)
  - sphinx_rtd_theme
  - sphinx-gallery

  # Utils
  - psutil
